server:
  servlet:
    context-path: /wholesale
  port: 9080

spring:
    application:
        name: Wholesale-Sample
    datasource:
      url: jdbc:h2:mem:anzDb;DB_CLOSE_DELAY=-1
      platform: h2
      username: h2user
      password: 
      driverClassName: org.h2.Driver
    h2:
      console:
        enabled: true
        path: /h2
         
    liquibase:
      change-log: classpath:db/liquibase-changelog.xml